# Site settings
title: STAT 385 @ UIUC
email: balamut2@illinois.edu
description: > 
  Website containing course material such as lectures and homework for STAT 385 @ UIUC
  during Summer 2016 Session 2
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stat385.thecoatlessprofessor.com" # the base hostname & protocol for your site
twitter_username: axiomsofxyz
github_username:  coatless

permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
timezone: America/Chicago
kramdown:
  input: GFM
  syntax_highlighter: rouge 